import { useState } from "react";
import { Plus, Minus, Sparkles, GitMerge, Info } from "lucide-react";
import type { ParallelSpec } from "../utils/topologyPresets";

interface Props {
  /** Initial values to seed the editor with — typically derived from the
   *  current stages on the API or from a sensible default. */
  initial?: Partial<ParallelSpec>;
  /** Apply handler. Receives the validated spec; the parent calls
   *  `applyTopologyPreset(apiId, spec)`. */
  onApply: (spec: ParallelSpec) => void;
  /** Optional cancel — closes the panel without applying. */
  onCancel?: () => void;
}

/**
 * Spec panel for the "parallel" (convergence) topology preset.
 *
 *   sub-chain 0 ──────┐
 *   sub-chain 1 ──────┤── Merge ── post-merge[0] ── … ── post-merge[N-1]
 *   sub-chain 2 ──────┘
 *
 * The user picks how many sub-chains, each chain's length, the merge
 * stage's display name, and how many stages chain after the merge. The
 * scaffold is generated by `applyTopologyPresetToApi` in store.ts.
 *
 * Validation is purely UI-side here (positive integers; ≥ 2 sub-chains;
 * each chain ≥ 1 stage). The store action does final coercion as well.
 */
export default function ParallelTopologyEditor({
  initial,
  onApply,
  onCancel,
}: Props) {
  const initialCount = clampInt(initial?.subChainCount ?? 2, 2, 8);
  const seedLengths = (initial?.subChainLengths ?? []).slice(0, initialCount);
  while (seedLengths.length < initialCount) seedLengths.push(3);

  const [subChainCount, setSubChainCount] = useState(initialCount);
  const [subChainLengths, setSubChainLengths] =
    useState<number[]>(seedLengths);
  const [mergeStageName, setMergeStageName] = useState(
    initial?.mergeStageName ?? "Merge"
  );
  const [postMergeCount, setPostMergeCount] = useState(
    Math.max(0, initial?.postMergeCount ?? 1)
  );

  const totalStages =
    subChainLengths.reduce((a, b) => a + Math.max(1, b), 0) +
    1 +
    Math.max(0, postMergeCount);

  const adjustChainCount = (delta: number) => {
    const next = clampInt(subChainCount + delta, 2, 8);
    setSubChainCount(next);
    const lens = subChainLengths.slice(0, next);
    while (lens.length < next) lens.push(3);
    setSubChainLengths(lens);
  };

  const setLengthAt = (idx: number, v: number) => {
    setSubChainLengths((p) =>
      p.map((x, i) => (i === idx ? Math.max(1, Math.floor(v) || 1) : x))
    );
  };

  const handleApply = () => {
    onApply({
      kind: "parallel",
      subChainCount,
      subChainLengths: subChainLengths.map((x) => Math.max(1, Math.floor(x))),
      mergeStageName: mergeStageName.trim() || "Merge",
      postMergeCount: Math.max(0, Math.floor(postMergeCount)),
    });
  };

  return (
    <div className="rounded-xl border border-violet-300/30 bg-gradient-to-br from-violet-300/8 via-cyan-300/5 to-pink-300/5 p-4 shadow-glowViolet">
      <div className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-white">
        <GitMerge size={14} className="text-violet-300" />
        Parallel topology
        <span className="ml-auto inline-flex items-center gap-1 rounded-md border border-white/10 bg-white/5 px-2 py-0.5 font-mono text-[10px] text-ink-200">
          {totalStages} stages total
        </span>
      </div>

      <div className="grid grid-cols-1 gap-3 sm:grid-cols-12">
        {/* Sub-chain count + adjuster */}
        <div className="sm:col-span-3">
          <Label>Sub-chains</Label>
          <div className="flex items-center gap-1">
            <button
              type="button"
              onClick={() => adjustChainCount(-1)}
              disabled={subChainCount <= 2}
              className="rounded-md border border-white/10 bg-white/5 p-1.5 text-ink-200 hover:bg-white/10 disabled:cursor-not-allowed disabled:opacity-40"
            >
              <Minus size={12} />
            </button>
            <span className="flex-1 rounded-md border border-white/10 bg-ink-900 px-2 py-1.5 text-center font-mono text-sm tabular-nums text-white">
              {subChainCount}
            </span>
            <button
              type="button"
              onClick={() => adjustChainCount(1)}
              disabled={subChainCount >= 8}
              className="rounded-md border border-white/10 bg-white/5 p-1.5 text-ink-200 hover:bg-white/10 disabled:cursor-not-allowed disabled:opacity-40"
            >
              <Plus size={12} />
            </button>
          </div>
        </div>

        {/* Merge stage name */}
        <div className="sm:col-span-5">
          <Label>Merge stage name</Label>
          <input
            value={mergeStageName}
            onChange={(e) => setMergeStageName(e.target.value)}
            className="w-full rounded-md border border-white/10 bg-ink-900 px-2.5 py-1.5 text-sm text-white outline-none focus:border-violet-300/50"
          />
        </div>

        {/* Post-merge count */}
        <div className="sm:col-span-4">
          <Label>Stages after merge</Label>
          <input
            type="number"
            min={0}
            value={postMergeCount}
            onChange={(e) =>
              setPostMergeCount(Math.max(0, Number(e.target.value) || 0))
            }
            className="cell-yellow w-full rounded-md px-2.5 py-1.5 text-right font-mono text-sm tabular-nums"
          />
        </div>
      </div>

      <div className="mt-3">
        <Label>Sub-chain lengths</Label>
        <div className="flex flex-wrap items-center gap-2">
          {subChainLengths.map((len, idx) => {
            const letter = String.fromCharCode(65 + idx);
            return (
              <div
                key={idx}
                className="flex items-center gap-1 rounded-md border border-white/10 bg-white/5 px-2 py-1"
              >
                <span className="font-mono text-[11px] font-bold text-violet-300">
                  {letter}
                </span>
                <input
                  type="number"
                  min={1}
                  value={len}
                  onChange={(e) => setLengthAt(idx, Number(e.target.value))}
                  className="cell-yellow w-14 rounded px-1.5 py-0.5 text-right font-mono text-xs tabular-nums"
                />
                <span className="text-[10px] text-ink-400">stages</span>
              </div>
            );
          })}
        </div>
      </div>

      <p className="mt-3 flex items-start gap-1.5 text-[11px] text-ink-300">
        <Info size={11} className="mt-0.5 shrink-0 text-violet-300" />
        Each sub-chain is a linear chain on its own. The merge stage pulls
        from every sub-chain's last stage, and the post-merge tail is
        another linear chain after the merge.
      </p>

      <div className="mt-4 flex items-center justify-end gap-2">
        {onCancel && (
          <button
            type="button"
            onClick={onCancel}
            className="rounded-lg border border-white/10 bg-white/5 px-3 py-1.5 text-xs font-semibold text-ink-200 hover:bg-white/10"
          >
            Cancel
          </button>
        )}
        <button
          type="button"
          onClick={handleApply}
          className="inline-flex items-center gap-1.5 rounded-lg border border-violet-300/40 bg-gradient-to-r from-violet-400/30 to-cyan-400/30 px-3 py-1.5 text-xs font-bold text-white hover:from-violet-400/50 hover:to-cyan-400/50 hover:shadow-glowViolet"
        >
          <Sparkles size={12} /> Apply parallel
        </button>
      </div>
    </div>
  );
}

function Label({ children }: { children: React.ReactNode }) {
  return (
    <div className="mb-1 text-[10px] font-bold uppercase tracking-wider text-ink-300">
      {children}
    </div>
  );
}

function clampInt(v: number, min: number, max: number): number {
  const n = Math.max(min, Math.min(max, Math.floor(v)));
  return Number.isFinite(n) ? n : min;
}
